FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-dbt.txt .
RUN pip install --no-cache-dir -r requirements-dbt.txt

COPY dbt/job_market ./job_market

WORKDIR /app/job_market

ENTRYPOINT ["dbt"]
